version: '2'
services:

    nginx:
      container_name: WEB_LB
      image: nginx:1.14
      restart: always
      network_mode:  host
      volumes:
        - "./public_html:/public_html"
        - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw"
       # - "./config/nginx/htpasswd:/etc/nginx/htpasswd:rw"
        - "./config/nginx/conf.d/:/etc/nginx/conf.d/:rw"
        
      logging:
        driver: "json-file"
        options:
          max-size: "20m"
          max-file: "3"
