version: "3"
services:
  app:
    build:
#      args:
#        user: root
#        uid: 0
      context: ./docker-conf/php
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./../public_html:/var/www
      - ./docker-conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker-conf/php/php.ini:/usr/local/etc/php/php.ini
    network_mode: host
    extra_hosts:
     # - "fluentd:127.0.0.1"
      - "core-02:192.168.0.92"
    environment:
      - HOST_HOSTNAME=${HOSTNAME}
    logging:
      driver: "json-file"
      options:
         max-size: "200k"
         max-file: "3"
#    networks:
#      - travellist

#  db:
#    image: mysql:5.7
#    container_name: travellist-db
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    volumes:
#      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
#    networks:
#      - travellist
#
  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
   # ports:
   #   - "8080"
    volumes:
      - ./../public_html:/var/www
      - ./docker-conf/nginx/conf.d/:/etc/nginx/conf.d
    network_mode: host
    environment:
      - HOST_HOSTNAME=${HOSTNAME}
    extra_hosts:
      - "app:127.0.0.1"
      - "fluentd:127.0.0.1"
    #networks:
    #  - travellist

#networks:
#  travellist:
#    driver: host

